name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Build wasm
        run: cargo wasm
      - name: Run tests
        run: cargo test --verbose -- --test-threads 1 # disable parallelism due to issue with test-tube that cause flaky tests
