name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
          components: llvm-tools-preview

      - name: Build wasm
        run: RUSTFLAGS="-C link-arg=-s" cargo build --release --lib --target wasm32-unknown-unknown --locked
      - name: Run tests
        run: cargo test --verbose -- --test-threads 1 # disable parallelism due to issue with test-tube that cause flaky tests
